using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using CNoom.UnityCodeGen.Editor;
using UnityEditor;
using UnityEngine;

namespace CUiAutoBind
{
    /// <summary>
    ///     代码生成器，负责生成和更新 UI 绑定代码
    /// </summary>
    public class CodeGenerator
    {

        private static readonly CodeGenTemplate autoFileTemplate =
            new CodeGenTemplate("AutoFileTemplate", Templates.AutoFileTemplate);

        private static readonly CodeGenTemplate manualFileTemplate =
            new CodeGenTemplate("ManualFileTemplate", Templates.ManualFileTemplate);
        private readonly UiBindConfig config;
        private readonly HashSet<string> generatedPaths = new HashSet<string>();

        public CodeGenerator(UiBindConfig config)
        {
            this.config = config;
        }

        /// <summary>
        ///     生成代码
        /// </summary>
        public void GenerateCode(GameObject target, List<AutoBindData> bindings)
        {
            if(target == null || config == null)
            {
                Debug.LogError("GenerateCode: Target or Config is null");
                return;
            }

            if(!config.IsValid())
            {
                Debug.LogError("GenerateCode: Config is invalid");
                return;
            }

            // 重置状态
            generatedPaths.Clear();

            // 获取 AutoBind 组件
            UiAutoBind rootUiAutoBind = target.GetComponent<UiAutoBind>();
            if(rootUiAutoBind == null)
            {
                Debug.LogError("GenerateCode: Target GameObject does not have AutoBind component");
                return;
            }

            // 递归生成代码
            GenerateRecursiveCode(rootUiAutoBind);

            AssetDatabase.Refresh();
        }

        /// <summary>
        ///     递归生成代码
        /// </summary>
        private void GenerateRecursiveCode(UiAutoBind uiAutoBind, string parentName = "")
        {
            // 获取这个 AutoBind 的自定义类名
            string className = uiAutoBind.GetUIClassName();
            GameObject targetObj = uiAutoBind.gameObject;

            // 生成当前对象的代码（始终使用 partial 模式）
            GenerateAutoFile(targetObj, uiAutoBind, className, parentName);
            GenerateManualFile(targetObj, className, parentName);

            // 递归生成子对象（只生成在 bindings 中显式绑定的 AutoBind 对象）
            List<AutoBindData> bindings = uiAutoBind.GetValidBindings();
            foreach (AutoBindData binding in bindings)
            {
                // 检查是否是 AutoBind 绑定
                if(binding.IsAutoBindReference() && binding.component != null)
                {
                    UiAutoBind childUiAutoBind = binding.component as UiAutoBind;
                    if(childUiAutoBind != null)
                    {
                        // 只递归生成显式绑定的子对象
                        GenerateRecursiveCode(childUiAutoBind, targetObj.name);
                    }
                }
            }
        }

        /// <summary>
        ///     生成自动生成的部分文件（xxx.Auto.cs）
        /// </summary>
        private void GenerateAutoFile(GameObject target, UiAutoBind uiAutoBind, string className,
            string parentName = "")
        {
            List<AutoBindData> bindings = uiAutoBind.GetValidBindings();

            // 确定文件路径（使用类名作为文件名）
            string filePath = GetFilePath(target.name, parentName, config.GetAutoGeneratedFilePath,
                $"{className}.Auto.cs");

            // 确保目录存在
            string directory = Path.GetDirectoryName(filePath);
            if(!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // 获取子对象 AutoBind 列表及其类名
            // 只有在 bindings 中显式绑定了子对象时，才生成对应的字段
            List<UiAutoBind> childAutoBinds = uiAutoBind.GetChildAutoBinds();
            List<ChildUIInfo> childUIInfos = new List<ChildUIInfo>();

            foreach (UiAutoBind childAutoBind in childAutoBinds)
            {
                // 检查是否在 bindings 中显式绑定了这个子对象
                bool isExplicitlyBound = bindings.Exists(b =>
                    b.IsAutoBindReference() &&
                    b.component == childAutoBind &&
                    b.generateField);

                // 只有显式绑定的子对象才生成字段
                if(isExplicitlyBound)
                {
                    string childClassName = childAutoBind.GetUIClassName();
                    string childFieldName = GetChildFieldName(childAutoBind);

                    childUIInfos.Add(new ChildUIInfo
                    {
                        className = childClassName,
                        fieldName = childFieldName
                    });
                }
            }

            // 生成代码内容
            string codeContent = GenerateAutoFileContent(className, bindings, childUIInfos);

            // 写入文件
            File.WriteAllText(filePath, codeContent, Encoding.UTF8);
            Debug.Log($"Auto file generated: {filePath}");
        }

        /// <summary>
        ///     获取文件路径（支持子对象）
        /// </summary>
        private string GetFilePath(string gameObjectName, string parentName,
            Func<string, string> basePathGetter, string fileName)
        {
            if(string.IsNullOrEmpty(parentName))
            {
                // 根对象：直接使用 GameObject 名称
                return basePathGetter(gameObjectName);
            }
            // 子对象：父对象目录 / 子对象名称
            string parentDir = Path.GetDirectoryName(basePathGetter(parentName));
            string childDir = Path.Combine(parentDir, gameObjectName);
            return Path.Combine(childDir, fileName);
        }

        /// <summary>
        ///     获取子对象在父对象中的字段名
        /// </summary>
        private string GetChildFieldName(UiAutoBind childUiAutoBind)
        {
            // 查找包含此子对象 AutoBind 的父对象
            Transform current = childUiAutoBind.transform;
            UiAutoBind parentUiAutoBind = null;

            while (current != null && parentUiAutoBind == null)
            {
                current = current.parent;
                if(current != null)
                {
                    parentUiAutoBind = current.GetComponent<UiAutoBind>();
                }
            }

            // 在父对象的 bindings 中查找对应的绑定
            if(parentUiAutoBind != null)
            {
                List<AutoBindData> bindings = parentUiAutoBind.GetValidBindings();
                foreach (AutoBindData binding in bindings)
                {
                    if(binding.IsAutoBindReference() && binding.component == childUiAutoBind)
                    {
                        return binding.fieldName;
                    }
                }
            }

            // 如果没有找到绑定，使用驼峰命名的 GameObject 名称
            string name = childUiAutoBind.gameObject.name;
            return char.ToLower(name[0]) + name.Substring(1);
        }

        /// <summary>
        ///     生成手动文件（xxx.cs）
        /// </summary>
        private void GenerateManualFile(GameObject target, string className, string parentName = "")
        {
            string filePath = GetFilePath(target.name, parentName, config.GetManualFilePath, $"{className}.cs");

            // 确保目录存在
            string directory = Path.GetDirectoryName(filePath);
            if(!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // 如果文件不存在，创建基本结构
            if(!File.Exists(filePath))
            {
                string codeContent = GenerateManualFileContent(className);
                File.WriteAllText(filePath, codeContent, Encoding.UTF8);
                Debug.Log($"Manual file created: {filePath}");
            }
        }

        /// <summary>
        ///     生成自动文件的内容（xxx.Auto.cs）
        /// </summary>
        private string GenerateAutoFileContent(string className, List<AutoBindData> bindings,
            List<ChildUIInfo> childUIInfos, List<ChildUIInfo> allChildInfos = null)
        {
            // 准备命名空间列表
            List<string> namespaces = CollectNamespaces(bindings);

            // 准备字段列表
            List<FieldInfo> fields = CollectFields(bindings);

            // 创建上下文
            CodeGenContext context = new CodeGenContext()
                .Set("Namespaces", namespaces)
                .Set("HasNamespace", !string.IsNullOrEmpty(config.namespaceName))
                .Set("Namespace", config.namespaceName)
                .Set("ClassName", className)
                .Set("ClassInheritance", config.GetClassInheritance())
                .Set("Fields", fields);

            // 使用模板渲染
            return CodeGen.Render(autoFileTemplate, context);
        }

        /// <summary>
        ///     生成手动文件的内容（xxx.cs）
        /// </summary>
        private string GenerateManualFileContent(string className)
        {
            // 创建上下文
            CodeGenContext context = new CodeGenContext()
                .Set("HasNamespace", !string.IsNullOrEmpty(config.namespaceName))
                .Set("Namespace", config.namespaceName)
                .Set("ClassName", className)
                .Set("ClassInheritance", config.GetClassInheritance());

            // 使用模板渲染
            return CodeGen.Render(manualFileTemplate, context);
        }

        /// <summary>
        ///     收集需要的命名空间
        /// </summary>
        private List<string> CollectNamespaces(List<AutoBindData> bindings)
        {
            HashSet<string> namespaces = new HashSet<string>();
            namespaces.Add("UnityEngine");
            namespaces.Add("UnityEngine.UI");

            // 添加生成的 UI 命名空间
            if(!string.IsNullOrEmpty(config.namespaceName))
            {
                namespaces.Add(config.namespaceName);
            }

            // 根据绑定组件类型添加命名空间
            foreach (AutoBindData binding in bindings)
            {
                if(binding == null || binding.component == null)
                    continue;

                // AutoBind 绑定不需要额外命名空间（已添加 UI 命名空间）
                if(binding.IsAutoBindReference())
                    continue;

                Type componentType = binding.component.GetType();
                string ns = componentType.Namespace;

                if(!string.IsNullOrEmpty(ns))
                {
                    namespaces.Add(ns);
                }
            }

            // 添加额外的命名空间配置
            if(config.additionalNamespaces != null)
            {
                foreach (string ns in config.additionalNamespaces)
                {
                    if(!string.IsNullOrEmpty(ns))
                    {
                        namespaces.Add(ns);
                    }
                }
            }

            return namespaces.OrderBy(n => n).ToList();
        }

        /// <summary>
        ///     收集字段信息
        /// </summary>
        private List<FieldInfo> CollectFields(List<AutoBindData> bindings)
        {
            List<FieldInfo> fields = new List<FieldInfo>();

            foreach (AutoBindData binding in bindings)
            {
                if(binding == null || binding.component == null || !binding.generateField)
                    continue;

                string fieldName = binding.fieldName;

                // 检查是否是 AutoBind 绑定
                if(binding.IsAutoBindReference())
                {
                    UiAutoBind childUiAutoBind = binding.component as UiAutoBind;
                    if(childUiAutoBind != null)
                    {
                        string childClassName = childUiAutoBind.GetUIClassName();
                        fields.Add(new FieldInfo
                        {
                            Attributes = "[SerializeField]",
                            Type = childClassName,
                            Name = fieldName
                        });
                        continue;
                    }
                }

                // 普通组件绑定
                string componentTypeName = StringUtil.GetComponentTypeName(binding.ComponentType);
                fields.Add(new FieldInfo
                {
                    Attributes = "[SerializeField]",
                    Type = componentTypeName,
                    Name = fieldName
                });
            }

            return fields;
        }

        /// <summary>
        ///     子对象 UI 信息
        /// </summary>
        private class ChildUIInfo
        {
            public string className; // 子对象的 UI 类名（来自子对象的 customClassName）
            public string fieldName; // 在父对象中的字段名
        }

        /// <summary>
        ///     字段信息
        /// </summary>
        private class FieldInfo
        {
            public string Attributes;
            public string Name;
            public string Type;
        }
    }
}