namespace CUiAutoBind
{
    /// <summary>
    ///     代码生成模板常量
    /// </summary>
    internal static class Templates
    {
        public const string AutoFileTemplate = @"// Auto-generated by CUIBind
// DO NOT EDIT MANUALLY IN THE AutoBind Generated REGION
// 自动生成的文件，请勿手动修改
// 重新生成时会完全覆盖此文件

{{#each Namespaces}}
using {{this}};
{{/each}}

{{#if HasNamespace}}
namespace {{Namespace}}
{
{{/if}}
    public partial class {{ClassName}}{{ClassInheritance}}
    {
{{#each Fields}}
        {{this.Attributes}}
        private {{this.Type}} {{this.Name}};
{{/each}}
    }
{{#if HasNamespace}}
}
{{/if}}
";

        public const string ManualFileTemplate = @"// Auto-generated by CUIBind
// DO NOT EDIT MANUALLY IN THE AutoBind Generated REGION
// 手动编写的文件，可以自由修改
// 重新生成自动文件时不会影响此文件
using UnityEngine;
using UnityEngine.UI;
{{#if HasNamespace}}
namespace {{Namespace}}
{
{{/if}}
    public partial class {{ClassName}}{{ClassInheritance}}
    {
        // 在这里添加你的业务逻辑和方法
    }
{{#if HasNamespace}}
}
{{/if}}
";
    }
}